# -*- coding: utf-8 -*-
"""PYTHON.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ISJd14dWFt7ZMptRn0exgPUVTjRhzMKR

Experiment 1
"""

n=int(input("enter a number : "))
fact=1
if(n%2==1):
  for i in range(2,n+1):
    fact*=i
  print(fact)
  print("the length is",len(str(fact)))
elif(n%2==0):
  pal=str(n)[::-1]
  if(pal==n):
    print("it is palindrome")
  else:
    print("it ia not a palindrome")

"""Experiment 2"""

a=input("enter a  word : ")
b=input("enter another word: ")
if b in a:
  print("YES")
else:
  print("NO")

"""Experiment 3(a)"""

li = list(input("Enter a list of numbers: "))
print(li)
first = li[0]
print("The first element of the list is:", first)
last = li[-1]
print("The last element of the list is:", last)

"""Experiment 3(b)"""

def ascending(lst):
    for i in range(len(lst) - 1):
        if lst[i] > lst[i + 1]:
            return False
    return True


lst = list(map(int,input("enter number : ").split()))


if ascending(lst):
    print("list is in ascending order")
else:
    print("list is not in ascending order")

"""Experiment 4(a)"""

my_tuple = tuple(map(int,input().split()))
string = ''.join(map(str, my_tuple))
print(" the string is",string)

"""Experiment 4(b)"""

tu=tuple(input("enter a tuple : " ))
tup=tu[::-1]
print(tup)

"""Experiment 5"""

set1 = set(input(" first set:  ").split())
set2 = set(input(" second set:  ").split())
if set1.issubset(set2):
  print("The first set is a subset of the second set")

else:
  print("It is not a subset")

"""Experiment 6"""

color = {}
n = int(input("Enter the number of elements "))
for i in range(n):
  key = input("Enter the key: ")
  value = input("Enter the value: ")
  color[key] = value
print("Dictionary elements are: \n")
for key, value in color.items():
  print(key, value)

"""Experiment 7(a)"""

import numpy as np
li = list(map(int,input("enter numbers : ").split()))
a = np.array(li)
print("The Numpy array is:",a)

"""Experiment 7(b)"""

import numpy as np
li = list(map(int,input("enter 1st array : ").split()))
tu = tuple(map(int,input("enter 2nd array : ").split()))

a1 = np.array(li)
a2 = np.array(tu)
a12 = np.concatenate((a1,a2))
print("The combined array is:",a12)
print(type(a12))

"""Experiment 8(a)"""

import numpy as np
import pandas as pd
a = np.random.rand(3)
print("Array:",a)
df1 = pd.DataFrame(a)
print("DataFrame:\n", df1,"\n", type(df1),)

s = pd.Series(a)
print("\nSeries:\n",s)
df2 = pd.DataFrame(s)
print("DataFrame:\n", df2, "\n", type(df2))

"""Experiment 8(b)"""

import pandas as pd
s1 = pd.Series([1, 2, 3, 4, 5])
s2 = pd.Series([2, 4, 6, 8, 10])
print("Addition: \n", s1 + s2)
print("Subtraction: \n", s1 - s2)
print("Multiplication: \n", s1 * s2)
print("Division: \n", s1 / s2)